source 'https://rubygems.org'

gem 'rack'
gem 'sinatra'
gem 'pry'
gem 'dotenv'
gem 'aws-sdk', '< 2'
gem 'ruby-hmac'
gem 'activesupport'

group :test do
  gem 'rspec'
  gem 'rack-test'
  gem 'webmock'
end
